### ISSUE TITLE
Doesn't work with key press in Plasma 5.8.4, need to hold super key for about a second

### ISSUE THREAD

**Issue by luipugs** [hanschen/ksuperkey#14] opened 2016-12-17 03:38 UTC
![system info](https://cloud.githubusercontent.com/assets/4028250/21284111/d601050c-c44c-11e6-8b26-6d3f6f2f36e7.png)

Installed from https://launchpad.net/~kubuntu-ppa/+archive/ubuntu/backports.

Debug output when pressing super key:
```
Intercepted key event 2, key code 133
Key pressed!
Intercepted key event 3, key code 133
Key released!
Generating Alt_L!
Generating F1!
Ignoring generated event.
Ignoring generated event.
Ignoring generated event.
Ignoring generated event.
```

Debug output when holding super key for about a second:
```
Intercepted key event 2, key code 133
Key pressed!
Intercepted key event 3, key code 133
Key released!
```

**Comment by wget** [comment] 2016-12-18 16:23
Cannot reproduce. Could you specify how you got the keyboard debug information? Keycode, cat code? What is the process to help us reproduce the issue? Thanks for your report btw.

**Comment by luipugs** [comment] 2016-12-18 17:55
I built ksuperkey from the latest in the master branch then I ran it using `ksuperkey -d`. Here's the output at the start.

```
$ ./ksuperkey -d
Assigned mapping from "Super_L" ( keysym 0xffeb, key code 133)
to "Alt_L" (keysym 0xffe9, key code 64)
to "F1" (keysym 0xffbe, key code 67)
sig_handler running...

```

**Comment by woxcab** [comment] 2016-12-23 03:39
I confirm. The same issue for the similar system:
![screenshot_20161223_063837](https://cloud.githubusercontent.com/assets/16160665/21446694/e3f097b4-c8e2-11e6-8e9a-3ce7fc45a4b1.png)

**Comment by woxcab** [comment] 2016-12-25 02:30
It seems `ksuperkey` is not necessary for plasma>=5.8:
https://blog.martin-graesslin.com/blog/2016/08/modifier-only-shortcuts-available-in-plasma-5-8/
Win key works perfectly for my system without started ksuperkey.

**Comment by hanschen** [comment] 2016-12-26 09:37
Yeah, I suspect that this is due to Plasma "catching" the key press. This was already stated in the README, but I've tried to make it clearer, with instructions on how to disable the Plasma mapping if you want to use ksuperkey to map Super to something else.

Closing this Issue, please reopen if the bug is due to something else.

**Closed by hanschen** 2016-12-26 09:37 UTC

**Comment by luipugs** [comment] 2016-12-26 11:20
Thanks, can confirm that it works without `ksuperkey`.
